version: '3.3'

services:

  fulltextsearchclient:
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true 
    volumes:
      - '.:/fulltextsearch-client'
      - '/fulltextsearch-client/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
